# Generated by Django 4.2.6 on 2023-10-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_wishlist_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='borrowed_by',
        ),
    ]
